### ISSUE TITLE
How to factory reset Iotanium dev board

### ISSUE THREAD

**Issue by ssingwork** [onicagroup/iotanium#1]
I modified boot.py and now I am not able to connect board. I tried serial port route with no luck.

**Comment by onica-emiller** [comment]
Hello @ssingwork , thank you for reaching out.  I've added detailed instructions for resetting the board to factory settings, which will write a new `boot.py` and get your board operating normally again.

https://docs.onica.com/projects/iotanium/en/preview/features/features.html#factory-reset

If you have problems flashing the board, please re-open this issue.  We'll have a side conversation to provide instructions to send your board in to exchange for a new board.

All the best!
